services:
  picarx-core-build:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - TAG=${TAG:-latest}
        - ARCH=${ARCH:-}
    image: ghcr.io/cau-se/arches-picar-x/picarx:${TAG:-latest}
    volumes:
      - ./core:/root/catkin_ws/src/core
    tty: true
    command: /bin/bash -c ""

networks:
  default:
    driver: bridge